[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install --break-system-packages -r ../requirements.txt"]

[start]
cmd = "PYTHONPATH=/app/..:${PYTHONPATH:-} uvicorn main:app --host 0.0.0.0 --port $PORT --log-level info"
